# Generated by Django 5.2.7 on 2025-11-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStoreApp', '0003_address_cart_order_review_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
