# Generated by Django 5.2.7 on 2025-11-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookStoreApp', '0005_alter_book_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='fiction', max_length=50),
        ),
    ]
